services:
  app:
    build:
      context: .
      target: builder
      args:
        DOCKER_BUILDKIT: 1
    image: shift-up-app
    env_file:
      - .env
      - .env.local
    container_name: shift-up_app_quasar
    volumes:
      - .:/app:rw
      - /var/www/html/front:/app/dist:rw
      - /app/node_modules
