services:
  app:
    build:
      context: .
      target: development
      args:
        DOCKER_BUILDKIT: 1
    image: shift-up-app
    env_file:
      - .env.local
      - .env
    container_name: shift-up_app_quasar
    ports:
      - '9000:9000'
    environment:
      COOLIFY_PR_ID: ${COOLIFY_PR_ID}
