# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
  storages:
    media.storage.local:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/%env(MEDIA_STORAGE_PATH_UPLOAD_DIR)%"
        permissions:
          file:
            public: 0766
            private: 0766
          dir:
            public: 0766
            private: 0766
    media.storage:
      adapter: "lazy"
      options:
        source: "%env(MEDIA_STORAGE)%"
