vich_uploader:
  db_driver: orm
  storage: flysystem
  mappings:
    file:
      uri_prefix: '%env(MEDIA_STORAGE_PREFIX_URL)%'
      upload_destination: media.storage
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
        options: { chars_per_dir: 1, dirs: 3 }
