#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

authenticate:
    path: /authenticate
    methods: ['POST']

token_refresh:
    path: /token/refresh
    methods: ['POST']