name: Deploy to Hosting on merge
"on":
  push:
    branches:
      - recette

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment:
      name: "Recette"
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environments for deploy
        run: |
          echo "Prepare quasar env"
          cd quasar/
          touch .env.local
          echo FRONT_URL=${{ vars.APP_FRONT_URL }} >> .env.local
          echo API_URL=${{ vars.APP_BACK_URL }} >> .env.local
          echo API_TEAM_DOCUMENTS_PATH=${{ vars.QUASAR_API_TEAM_DOCUMENTS_PATH }} >> .env.local
          cd ../api/
          echo "Prepare api env"
          touch .env.local
          echo APP_ENV=prod >> .env.local
          echo APP_SECRET=${{ secrets.API_APP_SECRET }} >> .env.local
          echo JWT_PASSPHRASE=${{ secrets.API_JWT_PASSPHRASE }} >> .env.local
          echo MISTRAL_API_KEY=${{ secrets.API_MISTRAL_API_KEY }} >> .env.local
          echo MISTRAL_MODEL=${{ secrets.API_MISTRAL_MODEL }} >> .env.local
          echo STRIPE_PUBLIC_KEY=${{ secrets.API_STRIPE_PUBLIC_KEY }} >> .env.local
          echo STRIPE_WEBHOOK_KEY=${{ secrets.API_STRIPE_WEBHOOK_KEY }} >> .env.local
          echo STRIPE_SECRET_KEY=${{ secrets.API_STRIPE_SECRET_KEY }} >> .env.local
          echo STRIPE_API_VERSION=${{ secrets.API_STRIPE_API_VERSION }} >> .env.local

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: recette-app
          path: .
          retention-days: 1
          compression-level: 6
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: "Recette"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: recette-app

      - name: Deploy to Hosting
        run: |
          echo "Deploying to Hosting"
          ssh-keygen -t rsa -b 4096 -C "github-actions" -N "" -f ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOSTING_SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          sshpass -p "${{ secrets.HOSTING_SSH_ROOT_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./ root@${{ secrets.HOSTING_SSH_HOST }}:${{ secrets.HOSTING_PATH }}
          sshpass -p "${{ secrets.HOSTING_SSH_ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.HOSTING_SSH_HOST }} "cd ${{ secrets.HOSTING_PATH }} && make clean-start-production && docker image prune -f && exit"
